CREATE TABLE [TbOperadora](
	[OpeId] [int] IDENTITY(1,1) NOT NULL,
	[OpeNome] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TbOperadora] PRIMARY KEY CLUSTERED 
(
	[OpeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE [TbPessoa](
	[PesId] [int] IDENTITY(1,1) NOT NULL,
	[PesNome] [varchar](150) NOT NULL,
 CONSTRAINT [PK_TbPessoa] PRIMARY KEY CLUSTERED 
(
	[PesId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [TbTelefone](
	[TelId] [int] IDENTITY(1,1) NOT NULL,
	[TelNumero] [varchar](20) NOT NULL,
	[OpeId] [int] NOT NULL,
	[PesId] [int] NOT NULL,
 CONSTRAINT [PK_TbTelefone] PRIMARY KEY CLUSTERED 
(
	[TelId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [TbTelefone]  WITH CHECK ADD  CONSTRAINT [FK_TbTelefone_TbOperadora] FOREIGN KEY([OpeId])
REFERENCES [TbOperadora] ([OpeId])
GO

ALTER TABLE [TbTelefone] CHECK CONSTRAINT [FK_TbTelefone_TbOperadora]
GO

ALTER TABLE [TbTelefone]  WITH CHECK ADD  CONSTRAINT [FK_TbTelefone_TbPessoa] FOREIGN KEY([PesId])
REFERENCES [TbPessoa] ([PesId])
GO

ALTER TABLE [TbTelefone] CHECK CONSTRAINT [FK_TbTelefone_TbPessoa]
GO


